config/routes.rb
require 'rackup'

Smbs::Application.routes.draw do

  root  :to       => 'welcome#show'
  
  post 'invite'   => 'invite#create'

  get  'login'    => 'sessions#new'
  post 'login'    => 'sessions#create'
  get  'logout'   => 'sessions#destroy'
  
  resources :user_activations, :password_resets
  
  
  # logged users tools
  # ==================
  resources :shorteners
  
  resources :statistics do
    member { get :details }
  end
  
  resources :barcodes do
    collection { post :create_link; post :create_sms; post :create_text }
    member     { get :download }
  end
  
  namespace :mobile do
    
    resources :campaigns do
       member     { get :settings;  put :assign_short_url; put :generate_short_url; put :approve }
       collection { get :ids_with_images }
       
       resources  :images
    end
    
  end
  
  
  # management console
  # ==================
  namespace :admin do

    resource  :dashboard do
      collection   { get :more_activity }
    end

    resources :invites
    
    resources :mobile_campaigns do
      collection { get :pending; get :published; get :draft }
      member     { put :publish; put :cancel; put :unpublish; put :archive }
    end
    
    resources :accounts do
      member           { get :settings; put :activate; put :disable; put :pretend; get :stop_pretend }
      resources :users do
        member         { put :invite; put :activate; put :disable;   }
      end
    end
    
    resources :locations do
      collection { get :countries; get :regions; get :cities }
      member     { put :update_city_display_name; put :update_country_display_name }
    end
  end
  
  namespace :reseller do
    resource :dashboard
  end
  
  namespace :business do
    resource :dashboard do
      collection   { get :more_activity }
    end
  end
  
  
  # rackup controllers
  # ==================
  get '/analytic/:source/:id/:member.json' => Rackup::AnalyticDataSourceApp.action(:fetch)
  get '/shorteners/:short/redirect'        => Rackup::ShortenersRedirectApp.action(:redirect), :constraints => { :short => /\w+(\.tel)?/ }
  get '/mobile_app/likeit/:id'             => Rackup::LikeitRedirectApp.action(:capture), :as => :mobile_app_likeit
  
  
  # mobile application routing schema
  # =================================
  namespace :mobile_app, :host => Global.host_mobi do
    get '/'                     => 'welcome#index',  :as => :root
    get '/campaigns/:id'        => 'campaigns#show', :as => :campaign
    get '/shorteners/:action'   => 'shorteners',     :as => :shorteners
  end
  
end

app/controllers/user_activations_controller.rb
#encoding: utf-8
class UserActivationsController < ApplicationController
  
  before_filter :require_no_user
  before_filter :load_user_using_perishable_token, :only => [ :edit, :update ]

  respond_to :html
  
  
  def update
    @user.require_non_blank_passwords = true
    @user.password                    = params[:user][:password]
    @user.password_confirmation       = params[:user][:password_confirmation]
    
    @user.update_dashboard(:user_activated, current_user)

    if @user.save
      flash[:notice] = "Аккаунт был успешно активирован. Теперь вы можете использовать свой email и пароль"
      @user.activate!
    end

    respond_with @user, :location => login_url
  end
  
  
  protected
  
  def load_user_using_perishable_token
    unless @user = User.find_using_perishable_token(params[:id])
      redirect_to login_url, :flash => { :error => 'Эта ссылка неверная или уже неактивна' }
    end
  end
  
end

app/views/user_activations/edit.html.erb
<div>
  <div class="block-center">
    <h1>Активируйте свой аккаунт для доступа к Yamco</h1>
    <%= error_messages_for :user, :header_message => nil, :message => nil -%>
  </div>

<%= form_for :user, :url => user_activation_path(@user.perishable_token), :html => { :method => :put } do |form| %>
  <div class="block-center">
    <ul class="input-list">
      <li class="item">
        <p><%= form.label :password, "пароль:" %></p>
        <p class="field"><%= form.password_field :password, :class => "text-field" %></p>
      </li>
      <li class="item">
        <p><%= form.label :password_confirmation, "введите пароль повторно:" %></p>
        <p class="field"><%= form.password_field :password_confirmation, :class => "text-field" %></p>
      </li>
    </ul>
  </div>
  <div class="block-center">
    <%= submit_tag "Активировать" %>
  </div>
<%end%>
</div>